### PR TITLE
apply eta-expansion

### PR DESCRIPTION
**Pull request by xgrommx**

### CODE REVIEW

**Comment by xgrommx** [comment]
cc @natefaubion

**Comment by natefaubion** [comment]
Is this just so you aren’t passing around so many dictionaries?

**Comment by xgrommx** [comment]
what do u mean?

**Comment by natefaubion** [comment]
You didn't provide a reason for this change. The difference I noticed is that you don't have to thread the HRecursive etc dictionaries around, since they are already in scope with `go`.

**Comment by xgrommx** [comment]
eta-expansion needed because we can get error like
```
RangeError: Maximum call stack size exceeded
```

**Comment by xgrommx** [comment]
By the way, how about higher order version of `Run`?
I mean `HFree` + https://github.com/xgrommx/purescript-hvariant?

**Comment by natefaubion** [comment]
I don't have time to work on HRun, but you are welcome to try out https://github.com/natefaubion/purescript-higher-order/pull/4 and see where you get 😄

**Pull request merged**
